language: java

jdk:
    - oraclejdk8

env:
    - TERM=dumb

script:
    - "./gradlew clean check -i --continue"

after_success:
    - "./gradlew jacocoRootReport coveralls"

branches:
  only:
    - master

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"